// Generated by ts-to-zod
import { z } from "zod";

export const latLngSchema = z.object({
  lat: z.number(),
  lng: z.number(),
});

export const addressDataSchema = latLngSchema.and(
  z.object({
    fullAddress: z.string(),
    placeId: z.string(),
  }),
);

export const deliveryPointSchema = z.object({
  id: z.number(),
  clientName: z.string(),
  addressData: addressDataSchema,
  crates: z.number(),
  preferredTime: z.string(),
});
